version: '3.4'

services:
  db:
    image: "mcr.microsoft.com/mssql/server:2017-latest"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=1Secure*Password1
    ports:
    - 80

  mmbasket:
    image: ${DOCKER_REGISTRY-}mmbasket
    build:
      context: .
      dockerfile: MMBasket/Dockerfile
    ports:
      - 5003:80
    depends_on:
      - db

  mmproducts:
    image: ${DOCKER_REGISTRY-}mmproducts
#    build:
#      context: .
#      dockerfile: MMProducts/Dockerfile
    ports:
      - 5002:80
    depends_on:
      - db

  mmusers:
    image: ${DOCKER_REGISTRY-}mmusers
#    build:
#      context: .
#      dockerfile: MMUsers/Dockerfile
    ports:
      - 5001:80
    depends_on:
      - db
        
  mmgateway:
    image: ${DOCKER_REGISTRY-}mmgateway
    build:
      context: .
      dockerfile: MMGateway/Dockerfile
    ports:
      - 5005:80
      - 8000:443
